//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class admins
{
    public int id { get; set; }
    public string account { get; set; }
    public string password { get; set; }
    public string email { get; set; }
    public string nickname { get; set; }
}

public partial class applications
{
    public int id { get; set; }
    public string email { get; set; }
    public string stuname { get; set; }
    public int state { get; set; }
    public string title { get; set; }
    public string body { get; set; }
    public string mobile { get; set; }
    public bool deal { get; set; }
    public int apptime { get; set; }
    public System.DateTime createtime { get; set; }
}

public partial class usercontact
{
    public int id { get; set; }
    public string usname { get; set; }
    public string usemail { get; set; }
    public int usclass { get; set; }
}
